"""Agent-run tracing: fire-and-forget structured traces to OpenObserve,
per-iteration timing breakdown, and Forgejo slowness alerting.

Every agent turn (success, stuck, error) emits a structured JSON trace with
the fields required by D-01.  The emission is fire-and-forget — it never blocks
the agent response and never raises if OpenObserve is down.

After turn completion ``check_and_alert_slowness()`` can be called to detect
individual LLM inference calls or tool executions that exceed the configured
thresholds (``nova_slow_llm_ms`` / ``nova_slow_tool_ms`` / ``nova_slow_turn_ms``)
and file a Forgejo issue with a 5-minute cooldown per alert type.
"""
from __future__ import annotations

import asyncio
import logging
import os
import time
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Any

import httpx

log = logging.getLogger("nova-core.tracer")

# ---------------------------------------------------------------------------
# Cooldown tracker for slowness alerts (Pitfall 4 mitigation)
# ---------------------------------------------------------------------------

_last_slow_alert: dict[str, float] = {}
"""Timestamp (time.monotonic) of the last alert per type — ``"llm"``, ``"tool"``, ``"turn"``."""

# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------


@dataclass
class IterationTrace:
    """Per-iteration timing breakdown within a single agent turn.

    Each iteration of the agent loop records one of these, capturing
    the LLM inference time and (if a tool was called) the tool execution
    time.
    """

    iteration_num: int
    """1-based iteration number within the turn."""

    llm_time_ms: int
    """Wall-clock milliseconds of the ``llm.chat()`` call in this iteration."""

    tool_time_ms: int
    """Wall-clock milliseconds of the ``tools.call_tool()`` call in this iteration."""

    tool_name: str
    """Name of the tool called in this iteration (empty string for final iteration)."""

    prompt_tokens: int = 0
    """Number of prompt (input) tokens consumed by the LLM call."""

    completion_tokens: int = 0
    """Number of completion (output) tokens generated by the LLM call."""


@dataclass
class AgentTrace:
    """Structured payload for a single agent-turn trace.

    All fields are set by the agent loop before calling ``emit_trace``.
    """

    channel: str
    """WhatsApp / telegram / api / voice"""

    user: str
    """Household name — the *target user* of the turn."""

    latency_ms: int
    """Wall-clock milliseconds of the entire ``run_agent`` call."""

    token_count: int
    """Total tokens consumed (prompt + eval) across all LLM calls in this turn."""

    tool_calls: list[dict] = field(default_factory=list)
    """Each entry: ``{"name": str, "status": str, "duration_ms": int}``.

    ``status`` is one of ``"completed"``, ``"denied"``, or ``"error"``.
    """

    errors: list[dict] = field(default_factory=list)
    """Each entry: ``{"tool": str, "error": str}`` — error message truncated to 500 chars."""

    iteration_count: int = 0
    """Number of LLM-tool round trips in this turn (1-based)."""

    got_stuck: bool = False
    """``True`` when the agent hit ``nova_max_iterations`` without producing a final answer."""

    timestamp: str = ""
    """ISO-8601 UTC timestamp (set at trace-creation time)."""

    turn_id: str = ""
    """UUID string for Postgres FK linkage to the ``agent_turns`` table."""

    iterations: list[dict] = field(default_factory=list)
    """Per-iteration breakdown — each entry is a dict matching ``IterationTrace`` fields."""


async def emit_trace(trace: AgentTrace) -> None:
    """Fire-and-forget POST of *trace* to the OpenObserve ``agent_traces`` stream.

    Reads credentials from environment variables (same pattern as
    ``log_anomaly._query_openobserve``).  If ``OPENOBSERVE_URL`` is empty/falsy
    the call is silently skipped.  All ``httpx`` exceptions are caught and
    logged at warning level — the caller is never blocked or raised through.
    """
    base_url = os.environ.get("OPENOBSERVE_URL", "").rstrip("/")
    if not base_url:
        log.debug("OPENOBSERVE_URL not set — skipping trace emission")
        return

    org = os.environ.get("OPENOBSERVE_ORG", "default")
    user = os.environ.get("OPENOBSERVE_USER", "")
    password = os.environ.get("OPENOBSERVE_PASSWORD", "")

    url = f"{base_url}/api/{org}/agent_traces/_json"
    payload = asdict(trace)

    auth = (user, password) if user and password else None

    try:
        async with httpx.AsyncClient(timeout=5) as client:
            resp = await client.post(url, json=payload, auth=auth)
            resp.raise_for_status()
    except httpx.HTTPError as exc:
        log.warning("emit_trace: OpenObserve POST failed — %s", exc)
    except Exception as exc:
        log.warning("emit_trace: unexpected error — %s", exc)


# ---------------------------------------------------------------------------
# Slowness alerting (D-06, D-07, D-08)
# ---------------------------------------------------------------------------

_SLOWNESS_COOLDOWN_S: float = 300.0
"""Minimum seconds between same-type slowness alerts (Pitfall 4)."""


async def _file_slow_alert(alert_type: str, trace: AgentTrace, detail: str) -> None:
    """Create a Forgejo issue for a slowness threshold breach (with cooldown).

    Checks the cooldown tracker before creating the issue.  Skips silently
    when Forgejo is not configured (same pattern as ``feedback.py:254-257``).
    """
    from .config import settings
    from .forgejo import ForgejoClient

    # Cooldown check
    now = time.monotonic()
    last = _last_slow_alert.get(alert_type, 0.0)
    if now - last < _SLOWNESS_COOLDOWN_S:
        log.debug(
            "slowness alert %s suppressed (cooldown: %.0fs remaining)",
            alert_type,
            _SLOWNESS_COOLDOWN_S - (now - last),
        )
        return

    # Skip silently if Forgejo is not configured
    if not settings.forgejo_url or not settings.forgejo_token:
        log.debug(
            "Forgejo not configured — skipping slowness alert (%s)",
            alert_type,
        )
        return

    client = ForgejoClient(
        base_url=settings.forgejo_url,
        repo=settings.forgejo_repo,
        token=settings.forgejo_token,
    )

    title = (
        f"[slowness] {alert_type.upper()} exceeded threshold on {trace.channel}"
    )

    try:
        issue_number = await client.create_issue(title, detail, labels=["slowness"])
        _last_slow_alert[alert_type] = now
        log.info(
            "Slowness issue #%d filed (%s: %s — %dms)",
            issue_number,
            alert_type,
            trace.channel,
            trace.latency_ms,
        )
    except Exception as exc:
        log.warning("Failed to file slowness alert (%s): %s", alert_type, exc)


def _build_slow_alert_detail(alert_type: str, trace: AgentTrace) -> str:
    """Build a structured Markdown body for a slowness alert issue."""
    lines: list[str] = []
    lines.append(f"## Slowness Alert — {alert_type.upper()}")
    lines.append("")
    lines.append(f"- **Channel:** {trace.channel}")
    lines.append(f"- **User:** {trace.user}")
    lines.append(f"- **Total turn latency:** {trace.latency_ms}ms")
    lines.append(f"- **Iteration count:** {trace.iteration_count}")
    lines.append(f"- **Timestamp:** {trace.timestamp or datetime.now(timezone.utc).isoformat()}")
    lines.append("")

    if trace.iterations:
        lines.append("### Per-Iteration Breakdown")
        lines.append("")
        lines.append("| Iteration | LLM (ms) | Tool (ms) | Tool Name | Tokens |")
        lines.append("|-----------|----------|-----------|-----------|--------|")
        for it in trace.iterations:
            lines.append(
                "| %s | %s | %s | %s | %d/%d |"
                % (
                    it.get("iteration_num", "?"),
                    it.get("llm_time_ms", "?"),
                    it.get("tool_time_ms", "?"),
                    it.get("tool_name", "-"),
                    it.get("prompt_tokens", 0),
                    it.get("completion_tokens", 0),
                )
            )
        lines.append("")

    lines.append("---")
    lines.append("*Reported by Nova tracer module*")
    return "\n".join(lines)


async def check_and_alert_slowness(trace: AgentTrace) -> None:
    """Check *trace* against configured thresholds and file alerts.

    Iterates over ``trace.iterations`` — if any iteration's ``llm_time_ms``
    exceeds ``nova_slow_llm_ms`` or ``tool_time_ms`` exceeds ``nova_slow_tool_ms``,
    or the total turn ``latency_ms`` exceeds ``nova_slow_turn_ms``, files
    a Forgejo issue with per-alert-type cooldown (default 300s).
    """
    from .config import settings

    detail = _build_slow_alert_detail("turn", trace)

    # Check total turn latency
    if trace.latency_ms > settings.nova_slow_turn_ms:
        log.info(
            "Slow turn detected: %dms (threshold: %dms) on %s/%s",
            trace.latency_ms,
            settings.nova_slow_turn_ms,
            trace.channel,
            trace.user,
        )
        await _file_slow_alert("turn", trace, detail)

    # Check per-iteration thresholds
    for it in (trace.iterations or []):
        llm_ms = it.get("llm_time_ms", 0) or 0
        tool_ms = it.get("tool_time_ms", 0) or 0
        tool_name = it.get("tool_name", "?")

        if llm_ms > settings.nova_slow_llm_ms:
            log.info(
                "Slow LLM call detected: %dms (threshold: %dms) iteration %s on %s/%s",
                llm_ms,
                settings.nova_slow_llm_ms,
                it.get("iteration_num", "?"),
                trace.channel,
                trace.user,
            )
            await _file_slow_alert("llm", trace, detail)

        if tool_ms > settings.nova_slow_tool_ms:
            log.info(
                "Slow tool call detected: %dms (threshold: %dms) tool=%s on %s/%s",
                tool_ms,
                settings.nova_slow_tool_ms,
                tool_name,
                trace.channel,
                trace.user,
            )
            await _file_slow_alert("tool", trace, detail)
